spring:
  datasource:
    postgres:
      jdbc-url: jdbc:postgresql://192.168.89.34:5432/sudinco
      username: core.user.back
      password: 'w>gWo2U8Ux0}R@'
      driver-class-name: org.postgresql.Driver

    mysql:
      jdbc-url: jdbc:mysql://192.168.61.9:3306/consultaWeb
      username: core.user.back
      password: 'JyVB1MHm?3VJ8;'
      driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 3f8d9a7c2e6b4f1a9d8c7e5f3a2b1c0d
  expiration: 9000000
  issuer: idp-panavial-backend

server:
  port: 9092